version: '3'

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    db_data:
        driver: local

services:

    #PHP Service
    app:
        container_name: look_care_app
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    nginx:
        container_name: look_care_nginx
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
            - "5173:5173"
        depends_on:
            - app
            - nodejs
        networks:
            - app-network

    db:
        container_name: look_care_db
        image: mysql:8.0
        restart: unless-stopped
        volumes:
            - db_data:/var/lib/mysql/
            - ./_docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: look-care
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - app-network

    nodejs:
        image: node:16
        container_name: look_care_npm
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - app-network
